version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    # volumes:
    #   - dbdata6:/data/db
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    restart: always
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    restart: always
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    restart: always
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=reservation
      - MONGO_USER=reservation
      - MONGO_PASSWORD=reservation
    depends_on:
      - mongodb

volumes:
  dbdata6:
